Simplify path references and improve shell code with comments

diff --git a/journali b/journali
--- a/journali
+++ b/journali
@@ -1,20 +1,26 @@
 #!/usr/bin/env bash
+
+# Environment variables
 BASE_COMMAND="docker-compose -f docker-compose.builder.yml run --rm"
 API_REPOSITORY="git@github.com:WesleyKlop/journali-api.git"
 API_FOLDER="journali-api"
 FRONTEND_REPOSITORY="git@github.com:WesleyKlop/journali-frontend.git"
 FRONTEND_FOLDER="journali-frontend"
 
-source ./dev.env
+# External variables also used by services
+source dev.env
 
-echo "      _                              _ _
+function print_banner() {
+    echo "      _                              _ _
      | |                            | (_)
      | | ___  _   _ _ __ _ __   __ _| |_
  _   | |/ _ \| | | | '__| '_ \ / _\` | | |
 | |__| | (_) | |_| | |  | | | | (_| | | |
  \____/ \___/ \__,_|_|  |_| |_|\__,_|_|_|
 "
+}
 
+# Initialize git repositories
 function init_repos() {
     if [ -d $API_FOLDER ] && [ -d $FRONTEND_FOLDER ]; then
         echo "Already initialized" 1>&2
@@ -30,24 +36,44 @@ function init_repos() {
     fi
 }
 
+# Print application help text
 function print_help() {
-    echo "Available commands:
- - init: Initialize the child repositories and docker requirements
- - install: Intall frontend node dependencies
- - migrate: Migrate the database
- - start: Start the development environment
- - stop: Stop the development environment
- - psql: Open a shell on the postgres database
- - yarn [command]: Run any yarn command on the frontend environment
- - cargo [command]: Run any cargo command on the api environment
- - diesel [command]: Run any diesel commando on the database environment
- - help: This command"
+    cat <<-EOF
+Journali CLI tool for managing a productive development environment.
+
+Usage:
+  journali [command] [argument ...]
+
+Available commands:
+  - init                   Initialize the project, environment and dependencies
+  - start                  Start the development environment
+  - stop                   Stop the development environment
+  - install                Intall frontend node dependencies
+  - migrate                Migrate the database
+  - psql                   Open a shell on the postgres database
+  - yarn [subcommand]      Run any yarn command on the frontend environment
+  - cargo [subcommand]     Run any cargo command on the api environment
+  - diesel [subcommand]    Run any diesel commando on the database environment
+  - help                   This command
+EOF
 }
 
+# Initializes requirements for the docker environment
 function init_docker() {
     docker network rm journali
     docker network create journali
 }
+
+# Installs dependencies for the frontend project using yarn
+function install_frontend_dependencies() {
+    if [ ! -d $FRONTEND_FOLDER ]; then
+        echo "The frontend repository could not be found. Maybe try running the \`init\` command first?" 1>&2
+        exit 1
+    fi
+    eval "$BASE_COMMAND" install
+}
+
+print_banner
 
 case $1 in
 init)
@@ -55,10 +81,12 @@ init)
     init_repos
     echo " - Creating docker networks"
     init_docker
+    echo " - Installing frontend dependencies"
+    install_frontend_dependencies
     ;;
 install)
-    echo " - Installing frontend dependencies for the frontend"
-    eval "$BASE_COMMAND" install
+    echo " - Installing frontend dependencies"
+    install_frontend_dependencies
     ;;
 start)
     echo " - Starting development environment"
@@ -73,7 +101,7 @@ yarn | cargo | diesel | migrate)
     eval "$BASE_COMMAND" "${*:1}"
     ;;
 psql)
-    docker-compose exec postgres psql -U $POSTGRES_USER -w -d $POSTGRES_DB
+    docker-compose exec postgres psql -U "$POSTGRES_USER" -w -d "$POSTGRES_DB"
     ;;
 help)
     print_help
